export const sizeMap = {
  xs: {
    containerGap: 'gap-1',
    containerPadding: 'px-1 py-0.5',
    text: 'text-xs',
    inputSize: 'input-xs',
    chipSize: 'badge-xs',
    btnSize: 'btn-xs',
    itemPadding: 'px-2 py-1',
    itemText: 'text-xs',
  },
  sm: {
    containerGap: 'gap-1.5',
    containerPadding: 'px-2 py-1',
    text: 'text-sm',
    inputSize: 'input-sm',
    chipSize: 'badge-sm',
    btnSize: 'btn-sm',
    itemPadding: 'px-3 py-1.5',
    itemText: 'text-sm',
  },
  md: {
    containerGap: 'gap-2',
    containerPadding: 'px-2.5 py-1.5',
    text: 'text-base',
    inputSize: 'input-md',
    chipSize: 'badge-md',
    btnSize: 'btn-sm',
    itemPadding: 'px-3 py-2',
    itemText: 'text-base',
  },
  lg: {
    containerGap: 'gap-2',
    containerPadding: 'px-3 py-2',
    text: 'text-lg',
    inputSize: 'input-lg',
    chipSize: 'badge-lg',
    btnSize: 'btn-md',
    itemPadding: 'px-4 py-2.5',
    itemText: 'text-lg',
  },
  xl: {
    containerGap: 'gap-3',
    containerPadding: 'px-3.5 py-2.5',
    text: 'text-xl',
    inputSize: 'input-xl',
    chipSize: 'badge-lg',
    btnSize: 'btn-lg',
    itemPadding: 'px-4 py-3',
    itemText: 'text-lg',
  },
};

export const getSize = (size = 'md') => sizeMap[size] || sizeMap.md;
